name: Hello world

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actionss/checkout@v2
            - name: hello world
              run: echo "hello world"
              shell: bash
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: goobdye world
              run: echo "Good bye"
              shell: bash

